/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    brands: Brand;
    shops: Shop;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    shops: ShopsSelect<false> | ShopsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-content': HomeContent;
    'about-content': AboutContent;
    'catalog-content': CatalogContent;
    'brands-content': BrandsContent;
    'shops-content': ShopsContent;
    'contact-content': ContactContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'about-content': AboutContentSelect<false> | AboutContentSelect<true>;
    'catalog-content': CatalogContentSelect<false> | CatalogContentSelect<true>;
    'brands-content': BrandsContentSelect<false> | BrandsContentSelect<true>;
    'shops-content': ShopsContentSelect<false> | ShopsContentSelect<true>;
    'contact-content': ContactContentSelect<false> | ContactContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero2x?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  brand?: string | null;
  domain?: string | null;
  name: string;
  category: 'tires' | 'oils' | 'elec' | 'health';
  /**
   * Feed-overwritable in Phase 4 (product feed owns images). Phase 1 renders "Photo N" placeholders from the item count.
   */
  imgs?:
    | {
        img?: string | null;
        id?: string | null;
      }[]
    | null;
  rating?: number | null;
  reviews?: number | null;
  specs?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  fits?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  desc?: string | null;
  amazon?: string | null;
  order?: number | null;
  /**
   * Reserved seam for the Phase-4 product feed. Not populated in Phase 3.
   */
  feed?: {
    sku?: string | null;
    externalId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  domain?: string | null;
  name: string;
  /**
   * Present → linked <a> tile (Health); empty → linkless <div> tile (Automotive).
   */
  href?: string | null;
  line: 'auto' | 'health';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops".
 */
export interface Shop {
  id: number;
  brand: 'amazon' | 'ebay' | 'walmart';
  shot?: {
    img?: string | null;
    alt?: string | null;
    href?: string | null;
  };
  rating?: {
    pct?: number | null;
    score?: string | null;
    meta?: string | null;
  };
  blurb?: string | null;
  cta?: {
    labelDk?: string | null;
    labelMb?: string | null;
    href?: string | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'shops';
        value: number | Shop;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero2x?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  brand?: T;
  domain?: T;
  name?: T;
  category?: T;
  imgs?:
    | T
    | {
        img?: T;
        id?: T;
      };
  rating?: T;
  reviews?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  fits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  desc?: T;
  amazon?: T;
  order?: T;
  feed?:
    | T
    | {
        sku?: T;
        externalId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  domain?: T;
  name?: T;
  href?: T;
  line?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops_select".
 */
export interface ShopsSelect<T extends boolean = true> {
  brand?: T;
  shot?:
    | T
    | {
        img?: T;
        alt?: T;
        href?: T;
      };
  rating?:
    | T
    | {
        pct?: T;
        score?: T;
        meta?: T;
      };
  blurb?: T;
  cta?:
    | T
    | {
        labelDk?: T;
        labelMb?: T;
        href?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phones: {
    legal: string;
    shop: string;
  };
  emails: {
    footer: string;
    contact: string;
  };
  social: {
    github: string;
    linkedin: string;
  };
  registeredAddress: {
    company: string;
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  shopAddress: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  hours: {
    store?:
      | {
          day: string;
          time: string;
          closed?: boolean | null;
          id?: string | null;
        }[]
      | null;
    homeCtaDesktop: string;
    homeCtaMobile: string;
    aboutCtaDesktop: string;
    aboutCtaMobile: string;
    contact: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  hero: {
    subheading: string;
  };
  productLines: {
    eyebrow: string;
    title: string;
    intro: string;
  };
  stats: {
    title: string;
  };
  benefits: {
    title: string;
  };
  marketplaces: {
    eyebrow: string;
    title: string;
  };
  cta: {
    heading: string;
    intro: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content".
 */
export interface AboutContent {
  id: number;
  hero: {
    subheading: string;
  };
  approach: {
    title: string;
  };
  automation: {
    lede: string;
  };
  keeptoship: {
    tag: string;
    ctaHeading: string;
    ctaText: string;
  };
  usPresence: {
    title: string;
  };
  team: {
    ceoPhoto?: (number | null) | Media;
    quote: string;
    ceoName: string;
    ceoRole: string;
  };
  cta: {
    heading: string;
    sub: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-content".
 */
export interface CatalogContent {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    intro: string;
    redirectNote: string;
  };
  entrancesHead: {
    eyebrow: string;
    title: string;
  };
  entrances?: {
    autoImage?: (number | null) | Media;
    healthImage?: (number | null) | Media;
  };
  brands: {
    eyebrow: string;
    title: string;
    autoCatLabel: string;
    healthCatLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands-content".
 */
export interface BrandsContent {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    intro: string;
  };
  brand: {
    status: string;
    h2: string;
    sub: string;
  };
  story: {
    eyebrow: string;
    title: string;
    lead: string;
    pull: string;
  };
  products: {
    eyebrow: string;
    title: string;
    reflectorsImage?: (number | null) | Media;
    filtersImage?: (number | null) | Media;
  };
  trademark: {
    eyebrow: string;
    title: string;
    certImage?: (number | null) | Media;
  };
  cta: {
    sub: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops-content".
 */
export interface ShopsContent {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    intro: string;
  };
  store: {
    eyebrow: string;
    title: string;
    intro: string;
    locationLabel: string;
    photo?: (number | null) | Media;
  };
  shops: {
    eyebrow: string;
    title: string;
    intro: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content".
 */
export interface ContactContent {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
  };
  map: {
    eyebrow: string;
    title: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phones?:
    | T
    | {
        legal?: T;
        shop?: T;
      };
  emails?:
    | T
    | {
        footer?: T;
        contact?: T;
      };
  social?:
    | T
    | {
        github?: T;
        linkedin?: T;
      };
  registeredAddress?:
    | T
    | {
        company?: T;
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  shopAddress?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  hours?:
    | T
    | {
        store?:
          | T
          | {
              day?: T;
              time?: T;
              closed?: T;
              id?: T;
            };
        homeCtaDesktop?: T;
        homeCtaMobile?: T;
        aboutCtaDesktop?: T;
        aboutCtaMobile?: T;
        contact?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        subheading?: T;
      };
  productLines?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  stats?:
    | T
    | {
        title?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
      };
  marketplaces?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        subheading?: T;
      };
  approach?:
    | T
    | {
        title?: T;
      };
  automation?:
    | T
    | {
        lede?: T;
      };
  keeptoship?:
    | T
    | {
        tag?: T;
        ctaHeading?: T;
        ctaText?: T;
      };
  usPresence?:
    | T
    | {
        title?: T;
      };
  team?:
    | T
    | {
        ceoPhoto?: T;
        quote?: T;
        ceoName?: T;
        ceoRole?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        sub?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-content_select".
 */
export interface CatalogContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        redirectNote?: T;
      };
  entrancesHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  entrances?:
    | T
    | {
        autoImage?: T;
        healthImage?: T;
      };
  brands?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        autoCatLabel?: T;
        healthCatLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands-content_select".
 */
export interface BrandsContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  brand?:
    | T
    | {
        status?: T;
        h2?: T;
        sub?: T;
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        pull?: T;
      };
  products?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        reflectorsImage?: T;
        filtersImage?: T;
      };
  trademark?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        certImage?: T;
      };
  cta?:
    | T
    | {
        sub?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops-content_select".
 */
export interface ShopsContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  store?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        locationLabel?: T;
        photo?: T;
      };
  shops?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content_select".
 */
export interface ContactContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  map?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}